### ISSUE TITLE
Chess Piece Checklist

### ISSUE THREAD

**Issue by zmroberts17** [c3n3/universali-ludo#1]
**Pre-1000:**
- [x] King: Jesus
- [x] Queen: Mary
- [x] Bishop: St. Peter
- [x] Bishop: St. Augustine
- [x] Knight: St. Paul
- [x] Knight: St. Michael the Archangel
- [x] Rook: St. Benedict
- [x] Rook: St. Mary Magdalene
- [x] Pawns: Angel 1

**Post-1000:**
- [x] King: Jesus (Sacred Heart)
- [x] Queen: Mary (Our Lady of Guadalupe)
- [x] Bishop: St. John Paul II
- [x] Bishop: St. Francis Xavier (not a bishop, but going to use unless something else shows up)
- [x] Knight: St. Joan of Arc
- [x] Knight: St. Ignatius of Loyola
- [x] Rook: St. Dominic
- [x] Rook: St. Francis of Assisi
- [x] Pawns: Angel 2
